[package]
name = "ss-project-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
ss-core = { path = "../ss-core" }
bon = { workspace = true }
serde_json = { workspace = true }
wherror = { workspace = true }
error-stack = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
