[package]
name = "ss-audio"
version = "0.1.0"
edition = "2024"

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true
ss-core = { path = "../ss-core" }
wherror = { workspace = true }
error-stack = { workspace = true }
rodio = { workspace = true }
derive_more = { workspace = true }
ctrlc = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[[bin]]
name = "ss-audio"
path = "src/main.rs"

[lints]
workspace = true
