//! Top-level project configuration.
//!
//! A project defines the output settings, audio source, and all clips
//! that make up a video. Projects are serialized as JSON and loaded by
//! the editor or headless renderer.

use crate::clip::ClipDef;

/// Top-level project configuration.
///
/// Deserialized from a JSON file generated by an agent or hand-authored.
/// Paths within the project are resolved relative to the project file's
/// parent directory.
#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct Project {
    /// Output resolution [width, height] in pixels.
    pub resolution: [u32; 2],
    /// Output frames per second.
    pub fps: u32,
    /// Total duration in seconds.
    pub duration: f64,
    /// Output file path.
    pub output: String,
    /// Audio configuration, if any.
    pub audio: Option<AudioConfig>,
    /// All clips in the project.
    pub clips: Vec<ClipDef>,
}

/// Audio source configuration.
#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct AudioConfig {
    /// Path to the audio file, relative to the project file.
    pub path: String,
    /// Start time offset in seconds.
    pub start_time: f64,
}
