//! Top-level project configuration.
//!
//! A project defines the output settings, audio source, and all items
//! that make up a video. Projects are serialized as JSON and loaded by
//! the editor or headless renderer.

pub mod loader;

use std::time::Duration;

use crate::item::ItemDef;

pub(crate) mod serde_duration_secs {
    use serde::Deserialize;
    use std::time::Duration;

    pub fn serialize<S>(dur: &Duration, s: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        s.serialize_f64(dur.as_secs_f64())
    }

    pub fn deserialize<'de, D>(d: D) -> Result<Duration, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let secs = f64::deserialize(d)?;
        Ok(Duration::from_secs_f64(secs))
    }
}

/// Video encoding configuration for the output file.
///
/// Controls H.264 encoding quality and compatibility settings.
/// All fields have sensible defaults; omitting the `encoding` key
/// in the project JSON produces the defaults.
#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct EncodingConfig {
    /// Constant Rate Factor (quality). Lower = better quality, larger file.
    /// Range: 0–51. Default: 18 (visually lossless).
    #[serde(default = "default_crf")]
    pub crf: u32,
    /// Encoding preset. One of: ultrafast, superfast, veryfast, faster,
    /// fast, medium, slow, slower, veryslow. Default: "medium".
    #[serde(default = "default_preset")]
    pub preset: String,
    /// Output pixel format. Default: "yuv420p" (maximum compatibility).
    #[serde(default = "default_pixel_format")]
    pub pixel_format: String,
}

fn default_crf() -> u32 {
    18
}

fn default_preset() -> String {
    "medium".into()
}

fn default_pixel_format() -> String {
    "yuv420p".into()
}

impl Default for EncodingConfig {
    fn default() -> Self {
        Self {
            crf: default_crf(),
            preset: default_preset(),
            pixel_format: default_pixel_format(),
        }
    }
}

/// Top-level project configuration.
///
/// Deserialized from a JSON file generated by an agent or hand-authored.
/// Paths within the project are resolved relative to the project file's
/// parent directory.
#[derive(Debug, Clone)]
pub struct Project {
    /// Output resolution [width, height] in pixels.
    pub resolution: [u32; 2],
    /// Output frames per second.
    pub fps: u32,
    /// Total duration.
    pub duration: Duration,
    /// Output file path.
    pub output: String,
    /// Background color as [R, G, B, A], default #2c2e34 (opaque dark gray).
    pub background: [u8; 4],
    /// Audio clips in the project. Empty if no audio.
    pub audio_clips: Vec<AudioClipDef>,
    /// Encoding settings for the output video.
    pub encoding: EncodingConfig,
    /// All items (images and groups) in the project.
    pub items: Vec<ItemDef>,
}

fn default_background() -> [u8; 4] {
    [0x2c, 0x2e, 0x34, 0xff]
}

/// Audio source configuration.
#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct AudioConfig {
    /// Path to the audio file, relative to the project file.
    pub path: String,
    /// Start time offset in seconds.
    pub start_time: f64,
}

/// A single audio clip on the timeline.
///
/// Audio clips are mixed together during playback and rendering.
/// Each clip has a path to an audio file, a time range, a track
/// assignment, and a volume level.
#[derive(Debug, Clone, serde::Deserialize, serde::Serialize)]
pub struct AudioClipDef {
    /// Unique identifier for reference.
    pub id: String,
    /// Path to the audio file, relative to the project file.
    pub path: String,
    /// Which audio track this clip occupies (for timeline display).
    pub track: u32,
    /// When this clip starts playing (seconds).
    pub start_time: f64,
    /// When this clip stops playing (seconds).
    pub end_time: f64,
    /// Volume level [0.0, 1.0]. Default: 1.0.
    #[serde(default = "default_volume")]
    pub volume: f32,
}

fn default_volume() -> f32 {
    1.0
}

/// Internal helper for deserializing both old (`clips`) and new (`items`) formats.
#[derive(Debug, Clone, serde::Deserialize)]
struct ProjectInner {
    pub resolution: [u32; 2],
    pub fps: u32,
    #[serde(with = "serde_duration_secs")]
    pub duration: Duration,
    pub output: String,
    #[serde(default = "default_background")]
    pub background: [u8; 4],
    /// Legacy single-audio field.
    pub audio: Option<AudioConfig>,
    /// Audio clips for multi-track audio support.
    #[serde(default)]
    pub audio_clips: Vec<AudioClipDef>,
    #[serde(default)]
    pub encoding: EncodingConfig,
    /// New-format items field.
    #[serde(default)]
    pub items: Vec<ItemDef>,
    /// Legacy clips field (backward compatibility).
    #[serde(default)]
    pub clips: Vec<ItemDef>,
}

impl<'de> serde::Deserialize<'de> for Project {
    fn deserialize<D>(deserializer: D) -> Result<Self, D::Error>
    where
        D: serde::Deserializer<'de>,
    {
        let inner = ProjectInner::deserialize(deserializer)?;

        // If items is empty but clips is present, map clips → items.
        let items = if inner.items.is_empty() && !inner.clips.is_empty() {
            inner.clips
        } else {
            inner.items
        };

        // If audio_clips is empty but audio is present, migrate.
        let audio_clips = if inner.audio_clips.is_empty() {
            inner
                .audio
                .map(|a| {
                    vec![AudioClipDef {
                        id: "audio".to_string(),
                        path: a.path,
                        track: 0,
                        start_time: a.start_time,
                        end_time: inner.duration.as_secs_f64(),
                        volume: 1.0,
                    }]
                })
                .unwrap_or_default()
        } else {
            inner.audio_clips
        };

        Ok(Project {
            resolution: inner.resolution,
            fps: inner.fps,
            duration: inner.duration,
            output: inner.output,
            background: inner.background,
            audio_clips,
            encoding: inner.encoding,
            items,
        })
    }
}

impl serde::Serialize for Project {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        #[derive(serde::Serialize)]
        struct ProjectOut<'a> {
            resolution: &'a [u32; 2],
            fps: &'a u32,
            #[serde(with = "serde_duration_secs")]
            duration: &'a Duration,
            output: &'a String,
            background: &'a [u8; 4],
            audio_clips: &'a [AudioClipDef],
            encoding: &'a EncodingConfig,
            items: &'a Vec<ItemDef>,
        }

        ProjectOut {
            resolution: &self.resolution,
            fps: &self.fps,
            duration: &self.duration,
            output: &self.output,
            background: &self.background,
            audio_clips: &self.audio_clips,
            encoding: &self.encoding,
            items: &self.items,
        }
        .serialize(serializer)
    }
}

#[cfg(test)]
#[allow(clippy::float_cmp)]
mod tests {
    use std::path::Path;

    use super::{EncodingConfig, Project};
    use crate::item::{FitMode, ItemContent, Sizing};
    use crate::path_resolve::resolve_path;
    use crate::test_utils::fixtures::build_project;

    // ============================================================
    // Encoding config tests
    // ============================================================

    #[test]
    fn project_without_encoding_gets_defaults() {
        // Given a project JSON without the encoding field.
        let json = r#"{
            "resolution": [1920, 1080],
            "fps": 60,
            "duration": 10.0,
            "output": "out.mp4",
            "items": []
        }"#;

        let project: Project = serde_json::from_str(json).unwrap();

        // Then encoding defaults are applied.
        assert_eq!(project.encoding.crf, 18);
        assert_eq!(project.encoding.preset, "medium");
        assert_eq!(project.encoding.pixel_format, "yuv420p");
    }

    #[test]
    fn project_with_explicit_encoding_preserves_values() {
        let json = r#"{
            "resolution": [1920, 1080],
            "fps": 60,
            "duration": 10.0,
            "output": "out.mp4",
            "encoding": { "crf": 23, "preset": "fast", "pixel_format": "yuv422p" },
            "items": []
        }"#;

        let project: Project = serde_json::from_str(json).unwrap();

        assert_eq!(project.encoding.crf, 23);
        assert_eq!(project.encoding.preset, "fast");
        assert_eq!(project.encoding.pixel_format, "yuv422p");
    }

    #[test]
    fn encoding_config_survives_serde_roundtrip() {
        let config = EncodingConfig {
            crf: 28,
            preset: "slow".into(),
            pixel_format: "yuv444p".into(),
        };

        let json = serde_json::to_string(&config).unwrap();
        let loaded: EncodingConfig = serde_json::from_str(&json).unwrap();

        assert_eq!(loaded.crf, 28);
        assert_eq!(loaded.preset, "slow");
        assert_eq!(loaded.pixel_format, "yuv444p");
    }

    // ============================================================
    // Project loading tests
    // ============================================================

    #[test]
    fn example_project_file_parses_with_correct_fields() {
        // Given the example project JSON file (still uses "clips" key).
        let json = std::fs::read_to_string("../../examples/basic_project.json")
            .expect("example project file should exist");

        // When parsing it (backward compatibility: "clips" → "items").
        let project: Project = serde_json::from_str(&json).expect("should parse successfully");

        // Then all fields are correct.
        assert_eq!(project.resolution, [1920, 1080]);
        assert_eq!(project.fps, 60);
        assert!((project.duration.as_secs_f64() - 30.0).abs() < 1e-5);
        assert_eq!(project.output, "output.mp4");
        assert_eq!(project.audio_clips.len(), 1);

        let audio_clip = &project.audio_clips[0];
        assert_eq!(audio_clip.path, "assets/song.mp3");
        assert!((audio_clip.start_time - 0.0).abs() < 1e-5);

        assert_eq!(project.items.len(), 1);
        let item = &project.items[0];
        assert_eq!(item.id, "background");
        assert!(matches!(&item.content, ItemContent::Image { path } if path == "assets/cover.png"));
        assert_eq!(item.track, 0);
        assert!((item.start_time - 0.0).abs() < 1e-5);
        assert!((item.end_time - 30.0).abs() < 1e-5);
        assert_eq!(item.z_index, 0);

        // Check sizing.
        assert!(
            matches!(&item.sizing, Sizing::FitRect { x, y, w, h, mode, anchor: _ }
                if *x == 0 && *y == 0 && *w == 1920 && *h == 1080 && matches!(mode, FitMode::Cover)
            )
        );

        // Check animations.
        assert_eq!(item.animations.len(), 4);
    }

    #[test]
    fn parse_minimal_project_without_optionals() {
        // Given a minimal project JSON with no audio and no animations.
        let json = r#"{
            "resolution": [1280, 720],
            "fps": 30,
            "duration": 10.0,
            "output": "out.mp4",
            "items": [{
                "id": "bg",
                "type": "image",
                "path": "bg.png",
                "track": 0,
                "start_time": 0.0,
                "end_time": 10.0,
                "z_index": 0
            }]
        }"#;

        // When parsing it.
        let project: Project = serde_json::from_str(json).expect("should parse");

        // Then optional fields get defaults.
        assert!(project.audio_clips.is_empty());
        let item = &project.items[0];
        assert_eq!(item.animations.len(), 0);
        assert_eq!(item.sizing, Sizing::default());
        assert_eq!(item.pivot, [0.5, 0.5]);
    }

    #[test]
    fn parse_invalid_json_returns_error() {
        // Given invalid JSON.
        let json = "{ not valid }";

        // When parsing it.
        let result = serde_json::from_str::<Project>(json);

        // Then an error is returned.
        assert!(result.is_err());
    }

    #[test]
    fn resolve_relative_path_joins_to_project_dir() {
        // Given a project file at /some/dir/project.json and a relative path.
        let project_file = Path::new("/some/dir/project.json");

        // When resolving a relative path.
        let resolved = resolve_path(project_file, "assets/cover.png").unwrap();

        // Then the path is joined to the project file's parent directory.
        assert_eq!(resolved, Path::new("/some/dir/assets/cover.png"));
    }

    #[test]
    fn resolve_absolute_path_returns_as_is() {
        // Given a project file and an absolute path.
        let project_file = Path::new("/some/dir/project.json");

        // When resolving an absolute path.
        let resolved = resolve_path(project_file, "/absolute/path/image.png").unwrap();

        // Then the absolute path is returned unchanged.
        assert_eq!(resolved, Path::new("/absolute/path/image.png"));
    }

    #[test]
    fn resolve_empty_string_returns_project_dir() {
        // Given a project file and an empty string path.
        let project_file = Path::new("/some/dir/project.json");

        // When resolving an empty string.
        let resolved = resolve_path(project_file, "").unwrap();

        // Then the result is the project file's parent directory.
        assert_eq!(resolved, Path::new("/some/dir"));
    }

    #[test]
    fn resolve_dotdot_path_joins_without_canonicalization() {
        // Given a project file and a path with parent directory references.
        let project_file = Path::new("/some/dir/project.json");

        // When resolving a path with ..
        let resolved = resolve_path(project_file, "../shared/assets/img.png").unwrap();

        // Then the path is joined (no canonicalization, just string join).
        assert_eq!(resolved, Path::new("/some/dir/../shared/assets/img.png"));
    }

    #[test]
    fn resolve_dot_path_joins_without_canonicalization() {
        // Given a project file and a path with a dot component.
        let project_file = Path::new("/some/dir/project.json");

        // When resolving a path with .
        let resolved = resolve_path(project_file, "./assets/img.png").unwrap();

        // Then the path is joined to the project directory.
        assert_eq!(resolved, Path::new("/some/dir/./assets/img.png"));
    }

    #[test]
    fn project_survives_serde_roundtrip() {
        // Given a project built programmatically.
        let project = build_project(vec![]);

        // When serializing and deserializing.
        let json = serde_json::to_string(&project).unwrap();
        let back: Project = serde_json::from_str(&json).unwrap();

        // Then the roundtrip preserves the data.
        assert_eq!(back.resolution, project.resolution);
        assert_eq!(back.fps, project.fps);
        assert!((back.duration.as_secs_f64() - project.duration.as_secs_f64()).abs() < 1e-5);
        assert_eq!(back.output, project.output);
    }

    #[test]
    fn project_with_multiple_items_preserves_item_order() {
        // Given a project JSON with three items in a specific order.
        let json = r#"{
            "resolution": [1920, 1080],
            "fps": 60,
            "duration": 10.0,
            "output": "out.mp4",
            "items": [
                {"id": "first", "type": "image", "path": "a.png", "track": 0, "start_time": 0.0, "end_time": 10.0, "z_index": 0},
                {"id": "second", "type": "image", "path": "b.png", "track": 1, "start_time": 0.0, "end_time": 10.0, "z_index": 1},
                {"id": "third", "type": "image", "path": "c.png", "track": 2, "start_time": 0.0, "end_time": 10.0, "z_index": 2}
            ]
        }"#;

        // When parsing it.
        let project: Project = serde_json::from_str(json).expect("should parse");

        // Then item IDs are preserved in their original order.
        assert_eq!(project.items.len(), 3);
        assert_eq!(project.items[0].id, "first");
        assert_eq!(project.items[2].id, "third");
    }

    #[test]
    fn item_without_sizing_defaults_to_natural() {
        // Given an item with sizing omitted (defaults to Natural).
        let json = r#"{
            "resolution": [1920, 1080],
            "fps": 60,
            "duration": 10.0,
            "output": "out.mp4",
            "items": [{"id": "bg", "type": "image", "path": "bg.png", "track": 0, "start_time": 0.0, "end_time": 10.0, "z_index": 0}]
        }"#;

        // When parsing it.
        let project: Project = serde_json::from_str(json).expect("should parse");

        // Then the item's sizing is Natural.
        assert_eq!(project.items[0].sizing, Sizing::Natural);
    }

    #[test]
    fn item_with_explicit_sizing_preserves_dimensions() {
        // Given an item with Explicit sizing.
        let json = r#"{
            "resolution": [1920, 1080],
            "fps": 60,
            "duration": 10.0,
            "output": "out.mp4",
            "items": [{"id": "bg", "type": "image", "path": "bg.png", "track": 0, "start_time": 0.0, "end_time": 10.0, "z_index": 0, "sizing": {"Explicit": {"width": 800, "height": 600}}}]
        }"#;

        // When parsing it.
        let project: Project = serde_json::from_str(json).expect("should parse");

        // Then the sizing is Explicit with the correct dimensions.
        assert!(
            matches!(&project.items[0].sizing, Sizing::Explicit { width, height } if *width == 800 && *height == 600)
        );
    }

    #[test]
    fn item_with_scale_sizing_preserves_factor() {
        // Given an item with Scale sizing.
        let json = r#"{
            "resolution": [1920, 1080],
            "fps": 60,
            "duration": 10.0,
            "output": "out.mp4",
            "items": [{"id": "bg", "type": "image", "path": "bg.png", "track": 0, "start_time": 0.0, "end_time": 10.0, "z_index": 0, "sizing": {"Scale": 1.5}}]
        }"#;

        // When parsing it.
        let project: Project = serde_json::from_str(json).expect("should parse");

        // Then the sizing is Scale with the correct factor.
        assert!(matches!(&project.items[0].sizing, Sizing::Scale(s) if (*s - 1.5).abs() < 1e-5));
    }

    #[test]
    fn item_with_fit_rect_sizing_preserves_contain_mode_and_dimensions() {
        // Given an item with FitRect Contain sizing.
        let json = r#"{
            "resolution": [1920, 1080],
            "fps": 60,
            "duration": 10.0,
            "output": "out.mp4",
            "items": [{"id": "bg", "type": "image", "path": "bg.png", "track": 0, "start_time": 0.0, "end_time": 10.0, "z_index": 0, "sizing": {"FitRect": {"x": 100, "y": 50, "w": 640, "h": 480, "mode": "Contain"}}}] }"#;

        // When parsing it.
        let project: Project = serde_json::from_str(json).expect("should parse");

        // Then the sizing is FitRect with Contain mode.
        assert!(
            matches!(&project.items[0].sizing, Sizing::FitRect { x, y, w, h, mode, anchor: _ }
                if *x == 100 && *y == 50 && *w == 640 && *h == 480 && matches!(mode, FitMode::Contain)
            )
        );
    }

    #[test]
    fn parse_project_missing_resolution_returns_error() {
        // Given a project JSON missing the required resolution field.
        let json = r#"{
            "fps": 60,
            "duration": 10.0,
            "output": "out.mp4",
            "items": []
        }"#;

        // When parsing it.
        let result = serde_json::from_str::<Project>(json);

        // Then an error is returned.
        assert!(result.is_err());
    }

    #[test]
    fn parse_project_missing_items_and_clips_defaults_to_empty() {
        // Given a project JSON missing both items and clips fields.
        let json = r#"{
            "resolution": [1920, 1080],
            "fps": 60,
            "duration": 10.0,
            "output": "out.mp4"
        }"#;

        // When parsing it.
        let project: Project = serde_json::from_str(json).expect("should parse");

        // Then items defaults to empty vec.
        assert!(project.items.is_empty());
    }

    #[test]
    fn parse_project_missing_all_required_fields_returns_error() {
        // Given a project JSON that is an empty object.
        let json = "{}";

        // When parsing it.
        let result = serde_json::from_str::<Project>(json);

        // Then an error is returned.
        assert!(result.is_err());
    }

    #[test]
    fn keyframe_without_easing_field_defaults_to_linear() {
        // Given a keyframe in JSON with no easing field.
        let json = r#"{
            "resolution": [1920, 1080],
            "fps": 60,
            "duration": 10.0,
            "output": "out.mp4",
            "items": [{
                "id": "test",
                "type": "image",
                "path": "img.png",
                "track": 0,
                "start_time": 0.0,
                "end_time": 10.0,
                "z_index": 0,
                "animations": [{
                    "property": "opacity",
                    "keyframes": [
                        {"time": 0.0, "value": 0.0},
                        {"time": 10.0, "value": 1.0}
                    ]
                }]
            }]
        }"#;

        // When parsing it.
        let project: Project = serde_json::from_str(json).expect("should parse");

        // Then both keyframes have Linear as their easing default.
        let keyframes = &project.items[0].animations[0].keyframes;
        assert_eq!(keyframes[0].easing, crate::animation::Easing::Linear);
    }

    #[test]
    fn second_keyframe_easing_also_defaults_to_linear() {
        // Given a keyframe in JSON with no easing field on the second keyframe.
        let json = r#"{
            "resolution": [1920, 1080],
            "fps": 60,
            "duration": 10.0,
            "output": "out.mp4",
            "items": [{
                "id": "test",
                "type": "image",
                "path": "img.png",
                "track": 0,
                "start_time": 0.0,
                "end_time": 10.0,
                "z_index": 0,
                "animations": [{
                    "property": "opacity",
                    "keyframes": [
                        {"time": 0.0, "value": 0.0},
                        {"time": 10.0, "value": 1.0}
                    ]
                }]
            }]
        }"#;

        // When parsing it.
        let project: Project = serde_json::from_str(json).expect("should parse");

        // Then the second keyframe also defaults to Linear.
        let keyframes = &project.items[0].animations[0].keyframes;
        assert_eq!(keyframes[1].easing, crate::animation::Easing::Linear);
    }

    #[test]
    fn parse_legacy_audio_field_migrates_to_audio_clips() {
        // Given a project JSON with the old "audio" field and no "audio_clips".
        let json = r#"{
            "resolution": [1920, 1080],
            "fps": 60,
            "duration": 30.0,
            "output": "out.mp4",
            "audio": { "path": "song.mp3", "start_time": 2.0 },
            "items": []
        }"#;

        // When parsing it.
        let project: Project = serde_json::from_str(json).expect("should parse");

        // Then audio_clips has one element with the migrated data.
        assert_eq!(project.audio_clips.len(), 1);
        let clip = &project.audio_clips[0];
        assert_eq!(clip.id, "audio");
        assert_eq!(clip.path, "song.mp3");
        assert_eq!(clip.track, 0);
        assert!((clip.start_time - 2.0).abs() < 1e-5);
        assert!((clip.end_time - 30.0).abs() < 1e-5);
        assert!((clip.volume - 1.0).abs() < 1e-5);
    }

    #[test]
    fn audio_clips_takes_precedence_over_legacy_audio() {
        // Given a project JSON with both "audio" and "audio_clips".
        let json = r#"{
            "resolution": [1920, 1080],
            "fps": 60,
            "duration": 30.0,
            "output": "out.mp4",
            "audio": { "path": "old.mp3", "start_time": 0.0 },
            "audio_clips": [{ "id": "new", "path": "new.mp3", "track": 0, "start_time": 0.0, "end_time": 10.0, "volume": 0.5 }],
            "items": []
        }"#;

        // When parsing it.
        let project: Project = serde_json::from_str(json).expect("should parse");

        // Then the audio_clips data is used (not the legacy field).
        assert_eq!(project.audio_clips.len(), 1);
        assert_eq!(project.audio_clips[0].id, "new");
        assert_eq!(project.audio_clips[0].path, "new.mp3");
    }

    #[test]
    fn audio_clips_default_is_empty_vec() {
        // Given a project JSON with neither "audio" nor "audio_clips".
        let json = r#"{
            "resolution": [1920, 1080],
            "fps": 60,
            "duration": 10.0,
            "output": "out.mp4",
            "items": []
        }"#;

        // When parsing it.
        let project: Project = serde_json::from_str(json).expect("should parse");

        // Then audio_clips is empty.
        assert!(project.audio_clips.is_empty());
    }

    #[test]
    fn audio_clips_survives_serde_roundtrip() {
        // Given a project with multiple audio clips.
        let project = build_project(vec![]);

        // When serializing and deserializing.
        let json = serde_json::to_string(&project).unwrap();
        let back: Project = serde_json::from_str(&json).unwrap();

        // Then the audio_clips are preserved.
        assert_eq!(back.audio_clips.len(), project.audio_clips.len());
        for (a, b) in back.audio_clips.iter().zip(project.audio_clips.iter()) {
            assert_eq!(a.id, b.id);
            assert_eq!(a.path, b.path);
        }
    }

    #[test]
    fn audio_clip_def_deserializes_with_default_volume() {
        // Given an audio clip JSON without the volume field.
        let json = r#"{
            "id": "bg",
            "path": "song.mp3",
            "track": 0,
            "start_time": 0.0,
            "end_time": 30.0
        }"#;

        // When parsing it.
        let clip: super::AudioClipDef = serde_json::from_str(json).expect("should parse");

        // Then volume defaults to 1.0.
        assert!((clip.volume - 1.0).abs() < 1e-5);
    }

    #[test]
    fn serialize_omits_legacy_audio_field() {
        // Given a project with audio clips.
        let project = build_project(vec![]);

        // When serializing to JSON.
        let json = serde_json::to_string(&project).unwrap();

        // Then the JSON contains "audio_clips" but not "audio".
        assert!(json.contains("audio_clips"));
        // Verify by parsing as a JSON value: "audio_clips" present, "audio" absent.
        let as_value: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert!(as_value.get("audio_clips").is_some());
        assert!(as_value.get("audio").is_none());
    }

    #[test]
    fn serialize_uses_items_not_clips() {
        // Given a project.
        let project = build_project(vec![]);

        // When serializing to JSON.
        let json = serde_json::to_string(&project).unwrap();

        // Then the JSON uses "items" not "clips".
        let as_value: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert!(as_value.get("items").is_some());
        assert!(as_value.get("clips").is_none());
    }

    #[test]
    fn example_project_file_parses_with_audio_clips() {
        // Given the updated example project JSON (uses legacy "clips" key).
        let json = std::fs::read_to_string("../../examples/basic_project.json")
            .expect("example project file should exist");

        // When parsing it.
        let project: Project = serde_json::from_str(&json).expect("should parse successfully");

        // Then audio_clips has one entry with the correct path and timing.
        assert_eq!(project.audio_clips.len(), 1);
        let clip = &project.audio_clips[0];
        assert_eq!(clip.id, "background-music");
        assert_eq!(clip.path, "assets/song.mp3");
        assert_eq!(clip.track, 0);
        assert!((clip.start_time - 0.0).abs() < 1e-5);
        assert!((clip.end_time - 30.0).abs() < 1e-5);
        assert!((clip.volume - 1.0).abs() < 1e-5);
    }

    // ============================================================
    // Backward compatibility tests
    // ============================================================

    #[test]
    fn legacy_clips_field_maps_to_items() {
        // Given a project JSON with "clips" instead of "items".
        let json = r#"{
            "resolution": [1920, 1080],
            "fps": 60,
            "duration": 10.0,
            "output": "out.mp4",
            "clips": [
                {"id": "bg", "type": "image", "path": "bg.png", "track": 0, "start_time": 0.0, "end_time": 10.0, "z_index": 0}
            ]
        }"#;

        // When parsing it.
        let project: Project = serde_json::from_str(json).expect("should parse");

        // Then items is populated from the clips field.
        assert_eq!(project.items.len(), 1);
        assert_eq!(project.items[0].id, "bg");
    }

    #[test]
    fn items_field_takes_precedence_over_clips() {
        // Given a project JSON with both "items" and "clips".
        let json = r#"{
            "resolution": [1920, 1080],
            "fps": 60,
            "duration": 10.0,
            "output": "out.mp4",
            "items": [
                {"id": "new", "type": "image", "path": "new.png", "track": 0, "start_time": 0.0, "end_time": 10.0, "z_index": 0}
            ],
            "clips": [
                {"id": "old", "type": "image", "path": "old.png", "track": 0, "start_time": 0.0, "end_time": 10.0, "z_index": 0}
            ]
        }"#;

        // When parsing it.
        let project: Project = serde_json::from_str(json).expect("should parse");

        // Then items is used (not clips).
        assert_eq!(project.items.len(), 1);
        assert_eq!(project.items[0].id, "new");
    }

    #[test]
    fn group_item_serializes_and_deserializes() {
        // Given a project with a group item.
        let json = r#"{
            "resolution": [1920, 1080],
            "fps": 60,
            "duration": 10.0,
            "output": "out.mp4",
            "items": [
                {
                    "id": "my-group",
                    "type": "group",
                    "children": [
                        {"id": "child1", "type": "image", "path": "a.png", "track": 0, "start_time": 0.0, "end_time": 10.0, "z_index": 0}
                    ],
                    "track": 0,
                    "start_time": 0.0,
                    "end_time": 10.0,
                    "z_index": 0,
                    "animations": [
                        {"property": "opacity", "keyframes": [{"time": 0.0, "value": 0.5, "easing": "Linear"}]}
                    ]
                }
            ]
        }"#;

        // When parsing it.
        let project: Project = serde_json::from_str(json).expect("should parse");

        // Then the group is parsed correctly.
        assert_eq!(project.items.len(), 1);
        assert!(
            matches!(&project.items[0].content, ItemContent::Group { children } if children.len() == 1)
        );

        // When serializing and deserializing again (round-trip).
        let out_json = serde_json::to_string(&project).unwrap();
        let back: Project = serde_json::from_str(&out_json).expect("round-trip");
        assert_eq!(back.items.len(), 1);
        assert!(
            matches!(&back.items[0].content, ItemContent::Group { children } if children.len() == 1)
        );
    }
}
