[package]
name = "ss-compositor"
version = "0.1.0"
edition = "2024"

[dependencies]
ss-core = { path = "../ss-core" }
euclid = { workspace = true }
wherror = { workspace = true }
error-stack = { workspace = true }
image = { workspace = true }
imageproc = { workspace = true }
derive_more = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }
tempfile = "3"

[[bin]]
name = "ss-compositor"
path = "src/main.rs"

[[bin]]
name = "gen-test-images"
path = "src/bin/gen_test_images.rs"

[[bin]]
name = "gen-demo-images"
path = "src/bin/gen_demo_images.rs"
